name: Build openSenseMap language package

on:
  push:
    branches:
      - actions
  pull_request:
    branches:
      - actions

jobs:
  test:
    name: Test package
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
        env:
          CI: true
      - name: Archive language files
        uses: actions/upload-artifact@v2
        with:
          name: openSenseMap-i18n
          path: dist
